//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-applyDiscount-SSD_SERVICE_ID_sd_FsL050KH3xOHWWGn
import { applyDiscount as SSD_SERVICE_ID_sd_FsL050KH3xOHWWGn } from './sd-services/applyDiscount';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-applyDiscount-SSD_SERVICE_ID_sd_FsL050KH3xOHWWGn
SSD_SERVICE_ID_sd_FsL050KH3xOHWWGn,
];
